# Generated by Django 5.1.6 on 2025-02-19 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignedInitals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='assignedName',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='prioName',
            field=models.CharField(default='Medium', max_length=55),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasksCheck',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='prio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(default=list),
        ),
    ]
