# Generated by Django 5.1.6 on 2025-02-24 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0003_userprofile_delete_user_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Der Name darf nur Buchstaben und Leerzeichen enthalten.', regex='^[A-Z][a-z]*\\s[A-Z][a-z]*$')]),
        ),
    ]
