# Generated by Django 5.1.6 on 2025-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0005_remove_userprofile_full_name_contact_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=55),
        ),
    ]
