# Generated by Django 5.1.6 on 2025-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0006_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, default='', max_length=55),
        ),
    ]
