# Generated by Django 5.1.6 on 2025-02-26 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0007_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedInitals',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignedName',
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join_db.contact')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join_db.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='assignedContacts',
            field=models.ManyToManyField(through='join_db.TaskAssignment', to='join_db.contact'),
        ),
    ]
