# Generated by Django 5.1.6 on 2025-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0008_remove_task_assignedinitals_remove_task_assignedname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignedInitals',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='assignedName',
            field=models.JSONField(default=list),
        ),
    ]
