# Generated by Django 5.1.6 on 2025-02-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0009_task_assignedinitals_task_assignedname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignedContacts',
        ),
    ]
