# Generated by Django 5.1.6 on 2025-02-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0010_remove_task_assignedcontacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAssignment',
        ),
    ]
