# Generated by Django 5.1.6 on 2025-02-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_db', '0011_delete_taskassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='join_db.userprofile'),
        ),
    ]
